### ISSUE TITLE
Add assetify.getAssetByID() function

### ISSUE THREAD

**Issue by thejdmego** [ov-sa/Assetify-Library#19]
Similar to assetify.getAsset(), but searches asset data by its model ID.

**Comment by Aviril** [comment]
Asset IDs are client side; However it could be synced but this would lead to completely inconsistency among server & client side resources.

To avoid this i have to generate custom assetify created IDs  just to provide consistency while GTA SA does the work as usual behind the scene but then everything will be broken because `getElementModel(element)` will return GTA SA ID which wont match with the custom created assetify ID unless the exports or something is used; Again irrelevant work here, when you can just use `assetType, assetName` which the library emphasizes on yet is consistent as indicated below.

```lua
local assetType, assetName, assetClump, clumpMaps = assetify.getElementAssetInfo(element)
local cAsset, cData = assetify.getAsset(assetType, assetName)

--Or
local cAsset, cData = assetify.getAsset(assetify.getElementAssetInfo(element))
```
https://github.com/ov-sa/Assetify-Library/wiki/Glossary:-APIs#-assetifygetelementassetinfo-shared
